### ISSUE TITLE
pbkdf2 OutputTooLong error

### ISSUE THREAD

**Issue by kevoh1516** [RustCrypto/password-hashes#329]
Trying to use the pbkdf2 algorithm with an output length greater than 64 but I keep getting a OutputTooLong error.

```
Pbkdf2.hash_password_customized(
    b"password",
    Some(Algorithm::Pbkdf2Sha512.ident()),
    None,
    Params {
        rounds: 100000,
        output_length: 128,
    },
    &SaltString::b64_encode(b"salt").unwrap(),
)
.unwrap();
```
Error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutputTooLong', src/main.rs:17:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/result.rs:1078:23
   4: pbkdf2test::main
             at ./src/main.rs:6:20
   5: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tarcieri** [comment]
You're using the "simple" API intended for password hashing as opposed to key derivation. 

This type enforces a maximum length of 64-bytes:

https://docs.rs/password-hash/latest/password_hash/struct.Output.html#constraints

To produce a longer output, you need to use the low-level interface:

https://docs.rs/pbkdf2/latest/pbkdf2/fn.pbkdf2.html

**Comment by polarathene** [comment]
> To produce a longer output, you need to use the low-level interface:
> 
> https://docs.rs/pbkdf2/latest/pbkdf2/fn.pbkdf2.html

Is there any examples to explain that page a bit better? Such as the `res: &mut [u8]` parameter, I have to go look up the "simple" API code and find this:

https://github.com/RustCrypto/password-hashes/blob/5192a53e1aa7aae6b2be2beaceb2a060b0545d3c/pbkdf2/src/simple.rs#L52-L62

So now I either copy/paste referencing this file, or I try understand what `out -> res` is from `Output::init_with(params.output_length, |out| {`, which is from a similar named crate `password-hash`, but in this org is a [subdir of the `RustCrypto/traits` repo](https://github.com/RustCrypto/traits/tree/master/password-hash). That brings to the other link you referenced where we can find the [`init_with()` method](https://docs.rs/password-hash/latest/password_hash/struct.Output.html#method.init_with):

> `F: FnOnce(&mut [u8]) -> Result<()>`
> 
> Initialize an [`Output`](https://docs.rs/password-hash/latest/password_hash/struct.Output.html) using the provided method, which is given a mutable byte slice into which it should write the output.
> 
> The `output_size` (in bytes) must be known in advance, as well as at least [`Output::MIN_LENGTH`](https://docs.rs/password-hash/latest/password_hash/struct.Output.html#associatedconstant.MIN_LENGTH) bytes and at most [`Output::MAX_LENGTH`](https://docs.rs/password-hash/latest/password_hash/struct.Output.html#associatedconstant.MAX_LENGTH) bytes.

[Looking into the source](https://docs.rs/password-hash/latest/src/password_hash/output.rs.html#147-167), I can see that `output_size` sets the slice length from a new/empty u8 array, that is then provided as the `&mut [u8]` closure param for the PBKDF2 method `res` param to use.

---

So `res` is "result"? And your advice here is to just provide your own fixed size mutable slice of desired length, instead of the `Output::init_with()` method? (_**EDIT:** Came across the [crates benches](https://github.com/RustCrypto/password-hashes/blob/5192a53e1aa7aae6b2be2beaceb2a060b0545d3c/pbkdf2/benches/lib.rs) and [tests](https://github.com/RustCrypto/password-hashes/blob/5192a53e1aa7aae6b2be2beaceb2a060b0545d3c/pbkdf2/tests/lib.rs) which demonstrate examples for exactly this well_)

---

Slightly off-topic, but for providing custom params such as rounds the docs did not cover that either, I see [`hash_password_customized`](https://docs.rs/password-hash/latest/password_hash/trait.PasswordHasher.html#tymethod.hash_password_customized) is a generic supported method, but as a new user to `password-hashes` (_via looking for a `pbkdf2` crate_) that was non-obvious until I read source and looked further into it like with the `res` parameter. I first thought I had to use the low-level interface to customize the rounds, a little doc example would help raise awareness of such :sweat_smile: 

The [tests at least provided an example of customizing the params from default](https://github.com/RustCrypto/password-hashes/blob/5192a53e1aa7aae6b2be2beaceb2a060b0545d3c/pbkdf2/tests/simple.rs#L32). Perhaps the README / docs could direct users that way for more examples if you don't think the docs should add more.

The main `password-hashes` README likewise, doesn't explain much about the common API (_neither did the PBKDF2 crate docs_). Perhaps that's covered somewhere else, just sharing my experience finding the useful crates and some friction with grokking how to use them.

---

One more piece of feedback, related to this issue was the [OWASP page warns about PBKDF2 implementations not handling the pre-hashing step correctly](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2) when input was larger than the block size used. As a user that also took a little bit more digging :sweat_smile: 

This at first seemed like it wasn't handling it from other implementations I had glanced over before:

https://github.com/RustCrypto/password-hashes/blob/5192a53e1aa7aae6b2be2beaceb2a060b0545d3c/pbkdf2/src/lib.rs#L120-L132

But then I tracked down the [PRF in the `hmac` crate](https://github.com/RustCrypto/MACs/blob/283d4395f01caea8e312cea7c8d9d480e379204a/hmac/src/lib.rs#L108-L131) (_`get_der_key()` which appears to be called from [`new_from_slice()`](https://github.com/RustCrypto/MACs/blob/283d4395f01caea8e312cea7c8d9d480e379204a/hmac/src/optim.rs#L153)_) seems to be where that is handled :+1:  (_confirmation would be appreciated_)

Probably doesn't need anything actionable, as other users landing on this issue with the same concern now have that information :)

**Comment by tarcieri** [comment]
Sorry to hear you're having trouble!

Part of the complexity here is that PBKDF2 fulfills a dual role: password hashing function as well as key derivation function, hence the need for two different APIs.

Password hashes serialize to specially formatted strings which encode their own parameters. In the case of the `password-hash` crate, that's the [PHC string format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md). The intended use is storing this string in a file or database, and using it for subsequent authentication attempts.

KDF usage, on the other hand, has only an arbitrary length binary output.

I agree the `res` name is somewhat confusing, and `out` would be better.
